const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Plugins.Dictionary,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{CurrentEmoji: 0},
	{MatchCount: 0},
	{MatchedList: 0},
	{SlotIndex: 0},
	{EmojiText: 0},
	{TypedInput: 0},
	{BasePart: 0},
	{LivesText: 0},
	{GameOverText: 0},
	{EmojiDB: 0},
	{Keyboard: 0},
	{ScoreText: 0},
	{MMTitleText: 0},
	{MML1Text: 0},
	{MML2Text: 0},
	{MMLevel3: 0},
	{Array_A: 0},
	{Array_B: 0},
	{Array_Shared: 0},
	{Audio: 0},
	{LivesRemaining: 0},
	{Score: 0},
	{Guess: 0},
	{EmojiPerWave: 0},
	{KeywordsRequired: 0},
	{SharedMode: 0}
];

self.InstanceType = {
	EmojiText: class extends self.ITextInstance {},
	TypedInput: class extends self.ITextInputInstance {},
	BasePart: class extends self.ISpriteInstance {},
	LivesText: class extends self.ITextInstance {},
	GameOverText: class extends self.ITextInstance {},
	EmojiDB: class extends self.IDictionaryInstance {},
	Keyboard: class extends self.IInstance {},
	ScoreText: class extends self.ITextInstance {},
	MMTitleText: class extends self.ITextInstance {},
	MML1Text: class extends self.ITextInstance {},
	MML2Text: class extends self.ITextInstance {},
	MMLevel3: class extends self.ITextInstance {},
	Array_A: class extends self.IArrayInstance {},
	Array_B: class extends self.IArrayInstance {},
	Array_Shared: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {}
}